Module Data
    Public Rendering As New List(Of String)({"[Rendering]",
                                            "GraphicsQuality=", 2,
                                            "TextureQuality=", 1,
                                            "ShadowQuality=", 1,
                                            "LightingQuality=", 2,
                                            "EffectsQuality=", 2,
                                            "TerrainQuality=", 3,
                                            "FloraQuality=", 2,
                                            "ModelQuality=", 3,
                                            "RenderDistance=", 4000,
                                            "Gamma=", 0.5,
                                            "VerticalFOV=", 70,
                                            "ParticleLOD=", 1,
                                            "FogShadowsEnable", 0,
                                            "MotionBlur=", 0,
                                            "VSync=", 0,
                                            "AO=", 0,
                                            "MaximumFPS", 200,
                                            "UseLod0a=",
                                            "BloomEnabed=", 0,
                                            "InfantryRenderDistance=", 500,
                                            "GroundVehicleRenderDistance=", 1000,
                                            "AirVehicleRenderDistance=", 2000,
                                            "UseGlobalRenderDistance=", 0,
                                            "ParticleDistanceScale=", 0.65,
                                            "Smoothing=", 0,
                                            "UseAspectFOV=", 0,
                                            "GpuPhysics=", 0,
                                            "ShadowManagerQuality=",
                                            "ShadowMapCount=",
                                            "ShadowMapQuality=",
                                            "ShadowNearDistance=",
                                            "ShadowFarDistance=",
                                            "ShadowRSM=",
                                            "ColorBlindFilterType=", 0,
                                            "ColorBlindFilterAmount=", 0,
                                            "ColorBlindFilterStrength", 0,
                                            "OverallQuality=", -1,
                                            "FSRQuality=", -1,
                                            "FSRSharpness=", 0,
                                            "DLSSQuality=", -1,
                                            "DLSSSharpness=", 0,
                                            "UseFences=",
                                            "AAQuality=", -1,
                                            "SmoothingMaxFramerate=", 60,
                                            "SmoothingMinFramerate=", 20,
                                            "UnderwaterGodRaysQuality=", 0,
                                            "SSLRQuality=", 0,
                                            "Tessellation=",
                                            "WaterQuality=", 0})
    Public Display As New List(Of String)({"[Display]",
                                          "Mode=",
                                          "FullscreenMode=",
                                          "FullscreenRefresh=",
                                          "FullscreenWidth=",
                                          "FullscreenHeight=",
                                          "WindowedWidth=",
                                          "WindowedHeight=",
                                          "Maximized=",
                                          "RenderQuality=", 1,
                                          "AllowToggleUI="})
    Public Sound As New List(Of String)({"[Sound]",
                                        "Master=", 0.5,
                                        "Music=", 0.5,
                                        "Game=", 0.5,
                                        "Dialog=", 0.5,
                                        "UI=", 0.5,
                                        "HitIndicator=", 1,
                                        "LowAmmoIndicator=", 1,
                                        "VehicleChatter=", 1,
                                        "IdleMusic=", 1,
                                        "MaxVoices=", 64,
                                        "UseFloat32Output=",
                                        "ExclusiveMode=",
                                        "UseHighQualityReverb="})
    Public Terrain As New List(Of String)({"[Terrain]",
                                          "RenderFlora=", "On"})
    Public General As New List(Of String)({"[General]",
                                          "AutoDetectPerformanceSettings=",
                                          "MouseSensitivity=", 0.3,
                                          "ScopedMouseSensitivity=", 0.3,
                                          "ADSMouseSensitivity=", 0.3,
                                          "VehicleMouseSensitivity=", 0.3,
                                          "FlightMouseSensitivity=", 0.3,
                                          "JoystickSensitivity=",
                                          "JoystickDeadzone=",
                                          "InvertVerticalLook=",
                                          "InvertVerticalFly=",
                                          "InvertTankSteering=",
                                          "MouseRawInput=", 1,
                                          "MouseSmoothing=",
                                          "ToggleCrouch=",
                                          "ZoomToggle=",
                                          "SprintToggle=",
                                          "SprintLegacyToggleMode=",
                                          "DrawHud=",
                                          "ReduceInputLag=",
                                          "FixedMinimap=",
                                          "Profanity=",
                                          "GamepadSmoothing=",
                                          "GamepadInvertLook=",
                                          "GamepadInvertFlight=",
                                          "GamepadEasyFlight=",
                                          "DecloakOnFire=",
                                          "AbilityQueueSeconds=",
                                          "VehicleGunnerMouseSensitivity="})
    Public UI As New List(Of String)({"[UI]",
                                     "CentralizedHudMode=", 1,
                                     "HudChatInactiveOpacity=",
                                     "HudShowIndicatorNames=", 1,
                                     "HudShowAlertTimer=", 1,
                                     "ShowReticleIFF=", 1,
                                     "HudShowHealth=", 1,
                                     "HudShowTopCompass=", 1,
                                     "HudShow3PVehicleReticle=", 0,
                                     "DrawMission=", 1,
                                     "DrawKillSpam=", 1,
                                     "DrawLootDrop=", 1,
                                     "TintModeReticuleStyle=", 0,
                                     "TintModeReticuleColor=", 0,
                                     "PlatoonSquadColor0=", 3781962,
                                     "PlatoonSquadColor1=", 10707465,
                                     "PlatoonSquadColor2=", 9578383,
                                     "PlatoonSquadColor3=", 65793,
                                     "TintModeFacility=", 1,
                                     "TintModePlayer=", 1,
                                     "TintModeMap=", 1,
                                     "TintModeFacilityOutfitWar=", 1,
                                     "TintModePlayerOutfitWar=", 0,
                                     "TintModeMapOutfitWar=", 1,
                                     "NoDeployZoneColor=", 13369344,
                                     "OrbitalStrikeColor=", 13421568,
                                     "OrbitalStrikeAlpha=", 0.1,
                                     "ShowGroupNotifications=", 1,
                                     "ShowOutfitNotifications=", 1,
                                     "HideWarpZoneConfirmation=", 0,
                                     "SelectedChatChannel=",
                                     "ChatFontSize=",
                                     "MapShowFactionColoredHotspots=",
                                     "MapActiveToggleView=",
                                     "MapFilterHeatMapMode=",
                                     "MapFilterShowInfluenceCloud=",
                                     "MapFilterShowGrid=",
                                     "MapFilterShowFacilities=",
                                     "MapFilterShowTerrain=",
                                     "MapFilterShowFacilityLinks=",
                                     "MapFilterShowTerritoryControl=",
                                     "MapFilterShowResource1=",
                                     "MapStatisticsView=",
                                     "MapFilterShowHotspots=",
                                     "MapCommandsSettingsShow2=",
                                     "MapCommandsSettingsShow3=",
                                     "MapCommandsSettingsAlpha3=",
                                     "TrackedDirectives=",
                                     "OutfitShowOfflineMembers=",
                                     "ShowVRTrainingTutorial=",
                                     "ShowDirectivesTutorial=",
                                     "ShowMapTutorial=",
                                     "ShowImplantTutorial=",
                                     "ShowTutorialIslandLandingPage=",
                                     "ShowOutfitsTutorial=",
                                     "LoadoutInfoInfiltrator=",
                                     "LoadoutInfoLightAssault=",
                                     "LoadoutInfoMedic=",
                                     "LoadoutInfoEngineer=",
                                     "LoadoutInfoHeavyAssault=",
                                     "LoadoutInfoMax=",
                                     "HiddenHUDIndicators=",
                                     "HideReticule=", 0,
                                     "HudChatOpacity=",
                                     "ConstructionFavorites="})
    Public AutoRefuse As New List(Of String)({"[AutoRefuse]",
                                             "FriendInvitation=",
                                             "DuelInvitation=",
                                             "GuildInvitation=",
                                             "HideUi=",
                                             "TradeRequest=",
                                             "HousingInvitation=",
                                             "GroupInvitation=",
                                             "SwapSeatRequest=",
                                             "Whispers="})
    Public ChatChannels As New List(Of String)({"[DisableChatChannelOptions]",
                                               "Squad=", 0,
                                               "Platoon=", 0,
                                               "Fireteam=", 0,
                                               "Leader=", 0,
                                               "Proximity=", 0,
                                               "Outfit=", 0,
                                               "Yell=", 0,
                                               "Region=", 0,
                                               "Mentor=", 0,
                                               "Social=", 0})
    Public Voice As New List(Of String)({"[Voice]",
                                        "Enable=", 1,
                                        "ReceiveVolume=", 50,
                                        "OutfitVolume=", 50,
                                        "SquadVolume=", 50,
                                        "RaidVolume=", 50,
                                        "ProximityVolume=", 50,
                                        "MicrophoneVolume=", 50,
                                        "Ducking=", 0.1,
                                        "EchoEnabled=", 1,
                                        "ProximityEnabled=", 1,
                                        "FactionEnabled=", 1,
                                        "GroupEnabled=", 1,
                                        "GroupLeaderEnabled=", 1,
                                        "RaidEnabled=", 1,
                                        "GuildEnabled=", 1,
                                        "RadioEnabled=", 1,
                                        "CBEnabled=", 1,
                                        "CustomEnabled=",
                                        "SubGroupEnabled=",
                                        "MuteInactiveChannels=",
                                        "PushToTalk="})
    Public Controls As New List(Of String)({"[Controls]",
                                           "CameraAutoAdjustment=",
                                           "ClickToMove=",
                                           "ClickToMoveRightButton=",
                                           "InfantryActionSetName=",
                                           "GroundVehicleSetName=",
                                           "AirVehicleActionSetName=",
                                           "Rumble=",
                                           "RailCamera="})
    Public Group As New List(Of String)({"[Group]",
                                        "AutoGroupOnLoginNew=", 0,
                                        "AutoGroupAsLeaderNew=", 0,
                                        "AutoGroupWithFriendsNew=", 0,
                                        "AutoGroupWithGuildNew=", 0,
                                        "AutoGroupOnLogin=", 0,
                                        "AutoGroupAsLeader=", 0,
                                        "AutoGroupwithFriends=", 0,
                                        "AutoGroupWithGuild=", 0})
    Public Guild As New List(Of String)({"[Guild]",
                                        "NotifyOnGuildPetitionRecieved="})
    Public Chat As New List(Of String)({"[Chat]",
                                       "HudChatInactiveOpacity=",
                                       "CanShowHudChat="})
    Public VoiceChat As New List(Of String)({"[VoiceChat]",
                                            "EchoEnabled=", 1,
                                            "EchoVolume=", 0.5,
                                            "ProximityEnabled=", 1,
                                            "ProximityVolume=", 0.5,
                                            "FactionEnabled=", 1,
                                            "FactionVolume=", 0.5,
                                            "GroupEnabled=", 1,
                                            "GroupVolume=", 0.5,
                                            "GroupLeaderEnabled=", 1,
                                            "GroupLeaderVolume=", 0.5,
                                            "RaidEnabled=", 1,
                                            "RaidVolume=", 0.5,
                                            "CBEnabled=", 1,
                                            "CBVolume=", 0.5,
                                            "CustomEnabled=", 1,
                                            "CustomVolume=", 0.5,
                                            "SubGroupEnabled=", 1,
                                            "SubGroupVolume=", 0.5,
                                            "InputDevice=", "Default System Device",
                                            "OutputDevice=", "Default System Device"})
    'Options below this comment are not currently, or may have never been used, but are listed here anyway
    'Public Social As New List(Of String)({"[Social]", "FriendNotifications="})
    'Public MinimapOptions As New List(Of String)({"[MinimapOptions]", "PathEnabled="})
    'Public Emote As New List(Of String)({"[Emote]", "Favorites="})
    'Public Logging As New List(Of String)({"[Logging]", "Directory=", "EnableDebugOutputString=", "LocalLogLevel=", "FileLogLevel=", "ServerLogLevel=", "OutputWindowLevel=", "LocalDirectory=", "FailureDirectory="})
    'Public UiDebug As New List(Of String)({"[UiDebug]", "WatchedColumns="})
    'Public CrashReporter As New List(Of String)({"[CrashReporter]", "MaxParameters=", "MaxUploaderPerDay=", "MaxUploadSec=", "MaxCrashAge=", "NoUploadFromInit=", "LocalFullDump=", "IncludeIndirectMemory=", "WaitForAttach=", "PipeCrashUploaderConsole="})
    'Public CrashUploader As New List(Of String)({"[CrashUploader]", "MaxPerDay=", "WaitForAttach=", "WriteResultsOnFailure="})
    'Public Promotion As New List(Of String)({"[Promotion]", "HasntOptedIn="})
    'Public Video As New List(Of String)({"[Video]", "VideoCapturePrefix="})
    'Public ImageCapture As New List(Of String)({"[ImageCapture]", "OutputFolder=", "OutputFilePrefix="})
    'Public VideoCapture As New List(Of String)({"[VideoCapture]", "Resolution=", "Quality=", "OutputFile=", "WorkingDir="})
    'Public VideoStreamer As New List(Of String)({"[VideoStreamer]", "Resolution=", "Fps=", "Kbps=", "MicRecordVolume=", "SpeakerRecordVolume=", "Username="})
    'Public Umbra As New List(Of String)({"[Umbra]", "Cull=", "TomeCollection="})
    'Public Graphics As New List(Of String)({"[Graphics]", "WindowWidth=", "WindowHeight="})
    Public bigOptions As Array = {Rendering, General, Terrain, UI, Sound, ChatChannels, Voice, VoiceChat, Display}
    Public curini As List(Of String) = Nothing
    Public curiniPath As String = "Useroptions.ini"
    Public iniini As List(Of String) = Nothing
    Public iniPath As String = "iniEdit.ini"
    Public iniEditOptions As New List(Of String)({"[iniEdit]",
                                                 "FontAutoReplace=",
                                                 "FontAutoReplace2=",
                                                 "FontFilePath=",
                                                 "FontFilePath2=",
                                                 "LocaleAutoReplace=",
                                                 "LocaleDirPath=",
                                                 "LocaleDatPath=",
                                                 "CommandAutoReplace=",
                                                 "DPI="})
    Public commandPath As String = "iniEditCommands.ini"
End Module